apiVersion: v1
data:
  MINIO_SECRET_KEY: ZXhhbXBsZTE=
  MYSQL_ROOT_PASSWORD: ZXhhbXBsZQ==
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"kind":"Secret","apiVersion":"v1","metadata":{"name":"osa-filemanagementservice-secret-file","creationTimestamp":null},"data":{"MINIO_SECRET_KEY":"ZXhhbXBsZTE=","MYSQL_ROOT_PASSWORD":"ZXhhbXBsZQ=="}}
  creationTimestamp: "2020-01-23T22:37:57Z"
  name: osa-filemanagementservice-secret-file
  namespace: default
  resourceVersion: "1738"
  selfLink: /api/v1/namespaces/default/secrets/osa-filemanagementservice-secret-file
  uid: b54e3de9-89ef-4671-9cac-2e9a8ee95a47
type: Opaque
