version: '3'
services:
    stresser:
        build: .
        volumes:
            - ./:/app
        environment:
                N1: 10
                N2: 100
                N3: 50
                N4: 20
                P1: 0.9
                P2: 0.87
                USERNAME: user@a.a
                PASSWORD: USERNAME
                ENDPOINT: http://osa.localhost/fms
                LOAD_SEC: 30
                EXISTEND_FILE_ID: 2
                NON_EXISTENT_FILE_ID: 3
                OUTPUT_FILE: metrics.csv
