apiVersion: v1
data:
  MYSQL_DATABASE: fms
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"kind":"ConfigMap","apiVersion":"v1","metadata":{"name":"osa-db-env-file","creationTimestamp":null},"data":{"MYSQL_DATABASE":"fms"}}
  creationTimestamp: "2020-01-26T22:21:22Z"
  name: osa-db-env-file
  namespace: default
  resourceVersion: "5868"
  selfLink: /api/v1/namespaces/default/configmaps/osa-db-env-file
  uid: ae6ed1e0-dc98-49b7-a622-462f37b75882
