apiVersion: v1
data:
  MINIO_SECRET_KEY: ZXhhbXBsZTE=
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"kind":"Secret","apiVersion":"v1","metadata":{"name":"osa-storage-secret-file","creationTimestamp":null},"data":{"MINIO_SECRET_KEY":"ZXhhbXBsZTE="}}
  creationTimestamp: "2020-01-23T20:02:53Z"
  name: osa-storage-secret-file
  namespace: default
  resourceVersion: "1377"
  selfLink: /api/v1/namespaces/default/secrets/osa-storage-secret-file
  uid: 581c70cc-c22c-4330-9e94-1ae3df236c3d
type: Opaque
