apiVersion: v1
data:
  MINIO_SECRET_KEY: ZXhhbXBsZTE=
  MYSQL_ROOT_PASSWORD: ZXhhbXBsZQ==
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"kind":"Secret","apiVersion":"v1","metadata":{"name":"osa-filemanagementservice-secret-file","creationTimestamp":null},"data":{"MINIO_SECRET_KEY":"ZXhhbXBsZTE=","MYSQL_ROOT_PASSWORD":"ZXhhbXBsZQ=="}}
  creationTimestamp: "2020-01-23T20:02:53Z"
  name: osa-filemanagementservice-secret-file
  namespace: default
  resourceVersion: "1374"
  selfLink: /api/v1/namespaces/default/secrets/osa-filemanagementservice-secret-file
  uid: f92fe27c-b7f0-421b-a8ef-2bd87fbc6e22
type: Opaque
