apiVersion: v1
data:
  MINIO_SECRET_KEY: ZXhhbXBsZTE=
  MYSQL_ROOT_PASSWORD: ZXhhbXBsZQ==
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"kind":"Secret","apiVersion":"v1","metadata":{"name":"osa-filemanagementservice-secret-file","creationTimestamp":null},"data":{"MINIO_SECRET_KEY":"ZXhhbXBsZTE=","MYSQL_ROOT_PASSWORD":"ZXhhbXBsZQ=="}}
  creationTimestamp: "2020-01-23T23:08:25Z"
  name: osa-filemanagementservice-secret-file
  namespace: default
  resourceVersion: "584"
  selfLink: /api/v1/namespaces/default/secrets/osa-filemanagementservice-secret-file
  uid: 48955a1d-19a1-4407-91ec-168807b73245
type: Opaque
