apiVersion: v1
data:
  MYSQL_ROOT_PASSWORD: ZXhhbXBsZQ==
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"MYSQL_ROOT_PASSWORD":"ZXhhbXBsZQ=="},"kind":"Secret","metadata":{"annotations":{},"creationTimestamp":"2020-01-23T11:19:29Z","name":"osa-db-secret-file","namespace":"default","resourceVersion":"3929","selfLink":"/api/v1/namespaces/default/secrets/osa-db-secret-file","uid":"1be40165-f8a3-4f05-86b8-a6e23327ed20"},"type":"Opaque"}
  creationTimestamp: "2020-01-23T11:19:29Z"
  name: osa-db-secret-file
  namespace: default
  resourceVersion: "4125"
  selfLink: /api/v1/namespaces/default/secrets/osa-db-secret-file
  uid: 1be40165-f8a3-4f05-86b8-a6e23327ed20
type: Opaque
