apiVersion: v1
data:
  MINIO_SECRET_KEY: ZXhhbXBsZTE=
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"kind":"Secret","apiVersion":"v1","metadata":{"name":"osa-storage-secret-file","creationTimestamp":null},"data":{"MINIO_SECRET_KEY":"ZXhhbXBsZTE="}}
  creationTimestamp: "2020-01-23T23:08:25Z"
  name: osa-storage-secret-file
  namespace: default
  resourceVersion: "588"
  selfLink: /api/v1/namespaces/default/secrets/osa-storage-secret-file
  uid: bb4c13f0-81b1-4574-bc70-8000a882a803
type: Opaque
