apiVersion: apps/v1
kind: Deployment
metadata:
  name: osa-nginx
spec:
  selector:
    matchLabels:
      app: osa-nginx
  template:
    metadata:
      labels:
        app: osa-nginx
    spec:
      containers:
      - name: osa-nginx
        image: apigw-nginx:v0
        ports:
        - containerPort: 80
      restartPolicy: Always
