version: '3'
services:
        objectstorageadapter:
                image: fms:v0
                restart: always
                links:
                        - mariadb
                ports:
                        - "8080:8080"
                environment:
                        - MYSQL_ROOT_PASSWORD: root
        db:
                image: mariadb
                restart: always
                environment:
                        - MYSQL_ROOT_PASSWORD: root
