version: '3'
services:
        osa-filemanagementservice:
                image: fms-prod:v0
                depends_on:
                        - osa-db
                        - osa-storage
                restart: always
                environment:
                        MYSQL_ROOT_USERNAME: root
                        MYSQL_ROOT_PASSWORD: example
                        MYSQL_HOST: osa-db
                        MYSQL_PORT: 3306
                        MYSQL_DBNAME: fms
                        MINIO_ACCESS_KEY: fms
                        MINIO_SECRET_KEY: example1    
                        MINIO_HOST: osa-storage
                        MINIO_PORT: 80
                        MINIO_DEFAULT_BUCKET: fms-default
                        EXTERNAL_URL: osa.localhost

        osa-db:
                image: mysql
                restart: always
                environment:
                        MYSQL_ROOT_PASSWORD: example
                        MYSQL_DATABASE: fms
                volumes:
                        - "ds-mysql-volume:/var/lib/mysql"
        
        osa-nginx:
              image: apigw-nginx:v0
              restart: always
              depends_on:
                    - osa-storage
                    - osa-filemanagementservice
              ports:
                    - "80:80"
#              environment:
#                      MINIO_HOST: osa-storage
#                      MINIO_PORT: 9090  
        
        osa-storage:
                image: minio/minio
                restart: always
                command: server --address :80 /data
                environment:
                        MINIO_ACCESS_KEY: fms
                        MINIO_SECRET_KEY: example1
                        MINIO_DOMAIN: osa.localhost
                volumes:
                        - "ds-minio-volume:/data"

volumes:
        ds-mysql-volume: {}
        ds-minio-volume: {}
