apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: osa-storage
spec:
  replicas: 3
  selector:
    matchLabels:
      app: osa-storage
  serviceName: "osa-storage"
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: osa-storage
    spec:
      containers:
      - name: osa-storage
        image: minio-custom:v0
        ports:
        - containerPort: 9000
        envFrom:
        - configMapRef:
          name: osa-storage-env-file
        - secretRef:
          name: osa-storage-secret-file
      - args:
        - server
        - /data
        volumeMounts:
        - mountPath: /data
          name: ds-minio-volume
      restartPolicy: Always
      volumes:
      - name: ds-minio-volume
        persistentVolumeClaim:
          claimName: ds-minio-volume
