apiVersion: v1
data:
  MINIO_SECRET_KEY: ZXhhbXBsZTE=
  MYSQL_ROOT_PASSWORD: ZXhhbXBsZQ==
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"kind":"Secret","apiVersion":"v1","metadata":{"name":"osa-filemanagementservice-secret-file","creationTimestamp":null},"data":{"MINIO_SECRET_KEY":"ZXhhbXBsZTE=","MYSQL_ROOT_PASSWORD":"ZXhhbXBsZQ=="}}
  creationTimestamp: "2020-01-26T22:21:22Z"
  name: osa-filemanagementservice-secret-file
  namespace: default
  resourceVersion: "5871"
  selfLink: /api/v1/namespaces/default/secrets/osa-filemanagementservice-secret-file
  uid: 971bcbda-518f-40cf-a9ba-c396b9ebedca
type: Opaque
