apiVersion: v1
data:
  MINIO_ACCESS_KEY: fms
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"kind":"ConfigMap","apiVersion":"v1","metadata":{"name":"osa-storage-env-file","creationTimestamp":null},"data":{"MINIO_ACCESS_KEY":"fms"}}
  creationTimestamp: "2020-01-23T20:02:53Z"
  name: osa-storage-env-file
  namespace: default
  resourceVersion: "1376"
  selfLink: /api/v1/namespaces/default/configmaps/osa-storage-env-file
  uid: 9a900be2-4394-44f2-aca3-e7f18c29f5ac
