apiVersion: v1
data:
  MYSQL_DATABASE: fms
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"kind":"ConfigMap","apiVersion":"v1","metadata":{"name":"osa-db-env-file","creationTimestamp":null},"data":{"MYSQL_DATABASE":"fms"}}
  creationTimestamp: "2020-01-23T20:02:53Z"
  name: osa-db-env-file
  namespace: default
  resourceVersion: "1367"
  selfLink: /api/v1/namespaces/default/configmaps/osa-db-env-file
  uid: 8bfcd899-8a61-441c-b393-7f7db9d89add
